### ISSUE TITLE
conky: X Error: type 0 Display 

### ISSUE THREAD

**Issue by presianbg** [philer/polycore#2]
Hi,

Your conky setup is awesome, thanks for it!
I'm trying to use it on Solus Linux (conky version - 1.11.5), but:

```
 conky -c conkyrc.lua 
conky: desktop window (160004d) is subwindow of root window (1f0)
conky: window type - override
conky: drawing to created window (0x4a00002)
conky: X Error: type 0 Display 23ef1d0 XID 23068749 serial 135 error_code 8 request_code 1 minor_code 0 other Display: 23ef1d0

Aborted
```
Would you be so kind to help me fixing it ?

Best Regards,
PY

**Comment by philer** [comment]
Hi,
that seems like an issue with conky itself. I don't think there's much I can do.  
Here's a similar issue which mentions `own_window_type = "override"`: https://github.com/brndnmtthws/conky/issues/424
Maybe if you change that it'll help.

**Comment by presianbg** [comment]
Dear @philer ,
Thanks for looking into this and helping me out.
I have changed ```own_window_type = "override"``` to ```own_window_type = "desktop" ```

And now conky starts, but with the following traceback:
```
conky -c examples/columns.lua 
conky: desktop window (8200257) is subwindow of root window (1f0)
conky: window type - desktop
conky: drawing to created window (0x2000002)
conky: drawing to double buffer
conky: statfs '/mnt/blackstor': No such file or directory
sh: nvidia-smi: command not found
examples/../src/widget.lua:1351: attempt to perform arithmetic on a nil value (local 'mem_total')
stack traceback:
	examples/../src/polycore.lua:53: in metamethod '__div'
	examples/../src/widget.lua:1351: in method 'init'
	examples/../src/util.lua:17: in field 'Gpu'
	examples/columns.lua:142: in function 'src/polycore.setup'
	examples/../src/polycore.lua:21: in function <examples/../src/polycore.lua:20>
	[C]: in function 'xpcall'
	examples/../src/polycore.lua:58: in function 'conky_setup'
examples/../src/polycore.lua:35: attempt to index a nil value (field 'renderer')
stack traceback:
	examples/../src/polycore.lua:53: in metamethod '__index'
	examples/../src/polycore.lua:35: in function <examples/../src/polycore.lua:26>
	[C]: in function 'xpcall'
	examples/../src/polycore.lua:63: in function 'conky_update'
conky: statfs '/mnt/blackstor': No such file or directory
```

I'm not sure if it is related to the ```own_window_type``` function or it's entirely new problem ?

**Comment by philer** [comment]
Hi, that's because you don't have nvidia-smi installed (notice the line that says `nvidia-smi: command not found`). If you have a nvidia gpu you can install that. If you don't then you won't be able to use the Gpu widget and need to remove it in layout.lua.
