### ISSUE TITLE
Missing License file.

### ISSUE THREAD

**Issue by simotek** [philer/polycore#5]
Hi,
I'd like to include this as part of a distro so its easier for more people to use, If your generally reasonably happy for people to use the lua code however then the MIT license is a good simple solution that's used with a number of other configs. All you'd need to do is copy the license text from here https://opensource.org/licenses/MIT into a copying or license file or maybe tot he bottom of your ReadMe.md if your happy with it, or pick any one of a number of other different licenses.

**Comment by simotek** [comment]
If it makes your life easier i'd also be happy to send it through as a pull request.

**Comment by philer** [comment]
Hey, I'll check on it later. MIT sounds reasonable.

**Comment by simotek** [comment]
Thanks

**Comment by philer** [comment]
Done, thanks for your patience. :)

**Comment by simotek** [comment]
Thankyou very much :-)
